version: '3.8'
services:
  webapp:
    build: ./server
    image: webapp
    command: npm run cli
    depends_on:
      - db
    ports:
      - 3000:3000
    network_mode: host




  db:
    image: postgres

    environment:
      - POSTGRES_DB=users
      - POSTGRES_USER=Rita
      - POSTGRES_PASSWORD=no_passwd
    ports:
      - 5432:5432
